export interface Exercise {
  id: string;
  name: string;
  muscleGroup: string;
  secondaryMuscles: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  equipment: string;
  instructions: string[];
  mistakes: string[];
  tips: string[];
  isHome: boolean;
  isGym: boolean;
  videoUrl?: string;
}

export const muscleGroups = ['chest', 'back', 'legs', 'shoulders', 'biceps', 'triceps', 'abs', 'cardio'] as const;
export const equipmentTypes = ['bodyweight', 'barbell', 'dumbbell', 'cable', 'machine', 'kettlebell', 'resistance band', 'none'] as const;
export const difficultyLevels = ['beginner', 'intermediate', 'advanced'] as const;

export const exercises: Exercise[] = [
  // CHEST (12)
  { id: 'e1', name: 'Push-Ups', muscleGroup: 'chest', secondaryMuscles: ['triceps', 'shoulders'], difficulty: 'beginner', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Place hands shoulder-width apart', 'Keep body in straight line', 'Lower chest to ground', 'Push back up explosively'],
    mistakes: ['Flaring elbows too wide', 'Sagging hips', 'Not going full range'],
    tips: ['Engage core throughout', 'Control the descent', 'Breathe out on push'] },
  { id: 'e2', name: 'Flat Bench Press', muscleGroup: 'chest', secondaryMuscles: ['triceps', 'shoulders'], difficulty: 'intermediate', equipment: 'barbell', isHome: false, isGym: true,
    instructions: ['Lie flat, feet on floor', 'Grip bar slightly wider than shoulders', 'Lower bar to mid-chest', 'Press up to lockout'],
    mistakes: ['Bouncing bar off chest', 'Lifting hips off bench', 'Uneven grip width'],
    tips: ['Retract shoulder blades', 'Drive feet into floor', 'Keep wrists straight'] },
  { id: 'e3', name: 'Incline Dumbbell Press', muscleGroup: 'chest', secondaryMuscles: ['shoulders', 'triceps'], difficulty: 'intermediate', equipment: 'dumbbell', isHome: false, isGym: true,
    instructions: ['Set bench to 30-45 degrees', 'Press dumbbells from shoulders', 'Squeeze at top', 'Lower with control'],
    mistakes: ['Bench angle too steep', 'Flaring elbows', 'Using momentum'],
    tips: ['Focus on upper chest squeeze', 'Keep slight arch', 'Match tempo on both arms'] },
  { id: 'e4', name: 'Cable Crossover', muscleGroup: 'chest', secondaryMuscles: ['shoulders'], difficulty: 'intermediate', equipment: 'cable', isHome: false, isGym: true,
    instructions: ['Stand center of cable station', 'Slight forward lean', 'Bring hands together in arc', 'Squeeze chest at bottom'],
    mistakes: ['Using too much weight', 'Bending elbows too much', 'Rounding back'],
    tips: ['Focus on stretch and squeeze', 'Keep slight elbow bend', 'Control the negative'] },
  { id: 'e5', name: 'Dumbbell Flyes', muscleGroup: 'chest', secondaryMuscles: ['shoulders'], difficulty: 'intermediate', equipment: 'dumbbell', isHome: false, isGym: true,
    instructions: ['Lie flat with dumbbells above chest', 'Open arms in wide arc', 'Feel stretch in chest', 'Bring back together'],
    mistakes: ['Going too heavy', 'Straightening arms fully', 'Dropping too deep'],
    tips: ['Keep slight elbow bend', 'Think hugging a tree', 'Lighter weight, more control'] },
  { id: 'e6', name: 'Diamond Push-Ups', muscleGroup: 'chest', secondaryMuscles: ['triceps'], difficulty: 'intermediate', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Hands close together forming diamond', 'Keep elbows close to body', 'Lower chest to hands', 'Push back up'],
    mistakes: ['Flaring elbows', 'Incomplete range', 'Sagging core'],
    tips: ['Great for inner chest', 'Scale on knees if needed', 'Pause at bottom'] },
  { id: 'e7', name: 'Decline Bench Press', muscleGroup: 'chest', secondaryMuscles: ['triceps'], difficulty: 'intermediate', equipment: 'barbell', isHome: false, isGym: true,
    instructions: ['Set bench to decline', 'Secure feet in pads', 'Lower bar to lower chest', 'Press to lockout'],
    mistakes: ['Too steep decline', 'Losing bar path', 'Rushing reps'],
    tips: ['Targets lower chest', 'Use spotter for safety', 'Control descent'] },
  { id: 'e8', name: 'Chest Dips', muscleGroup: 'chest', secondaryMuscles: ['triceps', 'shoulders'], difficulty: 'intermediate', equipment: 'bodyweight', isHome: false, isGym: true,
    instructions: ['Grip parallel bars', 'Lean forward slightly', 'Lower until upper arms parallel', 'Push back up'],
    mistakes: ['Going too deep', 'Not leaning forward', 'Swinging body'],
    tips: ['Lean forward for chest focus', 'Cross feet behind', 'Add weight when ready'] },
  { id: 'e9', name: 'Pec Deck Machine', muscleGroup: 'chest', secondaryMuscles: [], difficulty: 'beginner', equipment: 'machine', isHome: false, isGym: true,
    instructions: ['Sit with back flat', 'Place forearms on pads', 'Bring pads together', 'Squeeze and return'],
    mistakes: ['Using too much weight', 'Rounding shoulders forward', 'Jerky movements'],
    tips: ['Great isolation exercise', 'Focus on mind-muscle connection', 'Slow and controlled'] },
  { id: 'e10', name: 'Landmine Press', muscleGroup: 'chest', secondaryMuscles: ['shoulders', 'triceps'], difficulty: 'intermediate', equipment: 'barbell', isHome: false, isGym: true,
    instructions: ['Place barbell end in corner', 'Hold other end at shoulder', 'Press up at angle', 'Return with control'],
    mistakes: ['Arching back excessively', 'Losing core engagement', 'Wrong angle'],
    tips: ['Great for shoulder-friendly pressing', 'Can be done standing or kneeling', 'Unilateral option available'] },
  { id: 'e11', name: 'Resistance Band Chest Press', muscleGroup: 'chest', secondaryMuscles: ['triceps', 'shoulders'], difficulty: 'beginner', equipment: 'resistance band', isHome: true, isGym: false,
    instructions: ['Anchor band behind you', 'Hold handles at chest height', 'Press forward', 'Return slowly'],
    mistakes: ['Band too loose', 'Losing posture', 'Rushing movement'],
    tips: ['Great for home workouts', 'Constant tension throughout', 'Adjust resistance easily'] },
  { id: 'e12', name: 'Wide Push-Ups', muscleGroup: 'chest', secondaryMuscles: ['shoulders'], difficulty: 'beginner', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Hands wider than shoulder width', 'Lower chest to floor', 'Push back up', 'Maintain plank position'],
    mistakes: ['Hands too wide causing shoulder stress', 'Dropping head', 'Incomplete reps'],
    tips: ['Emphasizes chest stretch', 'Easier than standard push-ups', 'Good warm-up exercise'] },

  // BACK (12)
  { id: 'e13', name: 'Pull-Ups', muscleGroup: 'back', secondaryMuscles: ['biceps'], difficulty: 'intermediate', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Grip bar overhand shoulder-width', 'Pull chin above bar', 'Lower with control', 'Full extension at bottom'],
    mistakes: ['Kipping or swinging', 'Not full range', 'Chin not clearing bar'],
    tips: ['Squeeze lats at top', 'Dead hang between reps', 'Use bands for assistance'] },
  { id: 'e14', name: 'Barbell Bent-Over Row', muscleGroup: 'back', secondaryMuscles: ['biceps', 'shoulders'], difficulty: 'intermediate', equipment: 'barbell', isHome: false, isGym: true,
    instructions: ['Hinge at hips 45 degrees', 'Pull bar to lower chest', 'Squeeze shoulder blades', 'Lower with control'],
    mistakes: ['Rounding lower back', 'Using momentum', 'Standing too upright'],
    tips: ['Keep back flat', 'Think pulling with elbows', 'Pause at top'] },
  { id: 'e15', name: 'Deadlift', muscleGroup: 'back', secondaryMuscles: ['legs', 'abs'], difficulty: 'advanced', equipment: 'barbell', isHome: false, isGym: true,
    instructions: ['Stand with feet hip-width', 'Grip bar outside knees', 'Drive through heels', 'Lock hips at top'],
    mistakes: ['Rounding lower back', 'Bar drifting forward', 'Jerking the weight'],
    tips: ['Keep bar close to body', 'Brace core hard', 'Hip hinge not squat'] },
  { id: 'e16', name: 'Lat Pulldown', muscleGroup: 'back', secondaryMuscles: ['biceps'], difficulty: 'beginner', equipment: 'cable', isHome: false, isGym: true,
    instructions: ['Grip bar wide overhand', 'Pull to upper chest', 'Squeeze lats', 'Return slowly'],
    mistakes: ['Leaning too far back', 'Pulling behind neck', 'Using arms too much'],
    tips: ['Drive elbows down', 'Slight lean back is fine', 'Feel the stretch at top'] },
  { id: 'e17', name: 'Seated Cable Row', muscleGroup: 'back', secondaryMuscles: ['biceps'], difficulty: 'beginner', equipment: 'cable', isHome: false, isGym: true,
    instructions: ['Sit with feet on platform', 'Pull handle to abdomen', 'Squeeze shoulder blades', 'Extend arms slowly'],
    mistakes: ['Rounding forward', 'Using momentum', 'Not full extension'],
    tips: ['Keep chest up', 'Pause at contraction', 'Think of pulling elbows back'] },
  { id: 'e18', name: 'T-Bar Row', muscleGroup: 'back', secondaryMuscles: ['biceps', 'shoulders'], difficulty: 'intermediate', equipment: 'barbell', isHome: false, isGym: true,
    instructions: ['Straddle the bar', 'Grip close handle', 'Pull to chest', 'Lower with control'],
    mistakes: ['Too much body English', 'Rounding upper back', 'Grip slipping'],
    tips: ['Great for mid-back thickness', 'Use V-grip handle', 'Keep knees slightly bent'] },
  { id: 'e19', name: 'Dumbbell Row', muscleGroup: 'back', secondaryMuscles: ['biceps'], difficulty: 'beginner', equipment: 'dumbbell', isHome: true, isGym: true,
    instructions: ['One hand and knee on bench', 'Pull dumbbell to hip', 'Squeeze at top', 'Lower slowly'],
    mistakes: ['Rotating torso', 'Pulling to shoulder', 'Using momentum'],
    tips: ['Keep back flat', 'Row to hip not chest', 'Full stretch at bottom'] },
  { id: 'e20', name: 'Chin-Ups', muscleGroup: 'back', secondaryMuscles: ['biceps'], difficulty: 'intermediate', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Grip bar underhand', 'Pull chin over bar', 'Lower controlled', 'Full extension'],
    mistakes: ['Swinging', 'Half reps', 'Grip too narrow'],
    tips: ['More bicep activation than pull-ups', 'Great superset with pull-ups', 'Use slow negatives to build strength'] },
  { id: 'e21', name: 'Face Pulls', muscleGroup: 'back', secondaryMuscles: ['shoulders'], difficulty: 'beginner', equipment: 'cable', isHome: false, isGym: true,
    instructions: ['Set cable at face height', 'Pull rope to face', 'External rotate at end', 'Return slowly'],
    mistakes: ['Using too much weight', 'Not rotating externally', 'Pulling too low'],
    tips: ['Essential for shoulder health', 'High reps work best', 'Pull apart at end'] },
  { id: 'e22', name: 'Inverted Row', muscleGroup: 'back', secondaryMuscles: ['biceps', 'abs'], difficulty: 'beginner', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Hang under bar or table', 'Pull chest to bar', 'Keep body straight', 'Lower with control'],
    mistakes: ['Sagging hips', 'Not pulling high enough', 'Losing body alignment'],
    tips: ['Great pull-up progression', 'Adjust difficulty by foot position', 'Squeeze at top'] },
  { id: 'e23', name: 'Hyperextension', muscleGroup: 'back', secondaryMuscles: ['abs'], difficulty: 'beginner', equipment: 'machine', isHome: false, isGym: true,
    instructions: ['Position hips on pad', 'Cross arms on chest', 'Lower upper body', 'Extend back to neutral'],
    mistakes: ['Hyperextending past neutral', 'Using momentum', 'Going too fast'],
    tips: ['Strengthens lower back', 'Hold weight for progression', 'Controlled movement'] },
  { id: 'e24', name: 'Band Pull-Apart', muscleGroup: 'back', secondaryMuscles: ['shoulders'], difficulty: 'beginner', equipment: 'resistance band', isHome: true, isGym: true,
    instructions: ['Hold band at shoulder width', 'Pull apart to stretch band', 'Squeeze upper back', 'Return slowly'],
    mistakes: ['Using arms instead of back', 'Shrugging shoulders', 'Band too heavy'],
    tips: ['Great warm-up exercise', 'High reps build endurance', 'Daily use for posture'] },

  // LEGS (12)
  { id: 'e25', name: 'Barbell Squat', muscleGroup: 'legs', secondaryMuscles: ['abs', 'back'], difficulty: 'intermediate', equipment: 'barbell', isHome: false, isGym: true,
    instructions: ['Bar on upper back', 'Feet shoulder-width', 'Squat to parallel or below', 'Drive through heels'],
    mistakes: ['Knees caving in', 'Heels rising', 'Rounding lower back'],
    tips: ['King of all exercises', 'Brace core hard', 'Push knees over toes'] },
  { id: 'e26', name: 'Leg Press', muscleGroup: 'legs', secondaryMuscles: [], difficulty: 'beginner', equipment: 'machine', isHome: false, isGym: true,
    instructions: ['Place feet shoulder-width on platform', 'Lower until 90 degrees', 'Press back up', 'Don\'t lock knees'],
    mistakes: ['Locking knees at top', 'Lowering too deep', 'Bouncing at bottom'],
    tips: ['Foot position changes emphasis', 'Safer than squats for beginners', 'Great for volume'] },
  { id: 'e27', name: 'Romanian Deadlift', muscleGroup: 'legs', secondaryMuscles: ['back'], difficulty: 'intermediate', equipment: 'barbell', isHome: false, isGym: true,
    instructions: ['Hold bar at hip height', 'Hinge at hips, push butt back', 'Lower bar along legs', 'Feel hamstring stretch, return'],
    mistakes: ['Rounding lower back', 'Bending knees too much', 'Bar drifting from legs'],
    tips: ['Keep bar touching legs', 'Squeeze glutes at top', 'Best hamstring exercise'] },
  { id: 'e28', name: 'Bulgarian Split Squat', muscleGroup: 'legs', secondaryMuscles: ['abs'], difficulty: 'advanced', equipment: 'dumbbell', isHome: true, isGym: true,
    instructions: ['Rear foot on bench', 'Lower front knee to 90 degrees', 'Push through front heel', 'Keep torso upright'],
    mistakes: ['Leaning too far forward', 'Back foot doing too much work', 'Knee tracking inside'],
    tips: ['Great unilateral exercise', 'Fixes imbalances', 'Start with bodyweight'] },
  { id: 'e29', name: 'Lunges', muscleGroup: 'legs', secondaryMuscles: ['abs'], difficulty: 'beginner', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Step forward into lunge', 'Lower back knee toward floor', 'Push back to start', 'Alternate legs'],
    mistakes: ['Knee going past toes excessively', 'Losing balance', 'Short stride'],
    tips: ['Take a long stride', 'Keep torso upright', 'Can add dumbbells for progression'] },
  { id: 'e30', name: 'Leg Extension', muscleGroup: 'legs', secondaryMuscles: [], difficulty: 'beginner', equipment: 'machine', isHome: false, isGym: true,
    instructions: ['Sit with back against pad', 'Extend legs to straighten', 'Squeeze quads at top', 'Lower slowly'],
    mistakes: ['Locking knees hard', 'Using momentum', 'Going too heavy'],
    tips: ['Great quad isolation', 'Pause at top for burn', 'Control the negative'] },
  { id: 'e31', name: 'Leg Curl', muscleGroup: 'legs', secondaryMuscles: [], difficulty: 'beginner', equipment: 'machine', isHome: false, isGym: true,
    instructions: ['Lie face down on machine', 'Curl legs toward glutes', 'Squeeze hamstrings', 'Lower with control'],
    mistakes: ['Lifting hips off pad', 'Using momentum', 'Partial range'],
    tips: ['Essential for hamstring balance', 'Slow negatives build strength', 'Can do single leg'] },
  { id: 'e32', name: 'Calf Raises', muscleGroup: 'legs', secondaryMuscles: [], difficulty: 'beginner', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Stand on edge of step', 'Rise onto toes', 'Squeeze calves at top', 'Lower below step level'],
    mistakes: ['Not full range', 'Bouncing reps', 'Going too fast'],
    tips: ['High reps work best', 'Pause at top and bottom', 'Full stretch crucial'] },
  { id: 'e33', name: 'Goblet Squat', muscleGroup: 'legs', secondaryMuscles: ['abs'], difficulty: 'beginner', equipment: 'dumbbell', isHome: true, isGym: true,
    instructions: ['Hold dumbbell at chest', 'Squat deep with elbows between knees', 'Push knees out', 'Drive up through heels'],
    mistakes: ['Leaning forward', 'Not going deep enough', 'Losing the dumbbell position'],
    tips: ['Best squat for beginners', 'Teaches proper squat form', 'Great for mobility'] },
  { id: 'e34', name: 'Glute Bridge', muscleGroup: 'legs', secondaryMuscles: ['abs'], difficulty: 'beginner', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Lie on back, knees bent', 'Drive hips up', 'Squeeze glutes at top', 'Lower with control'],
    mistakes: ['Hyperextending lower back', 'Not squeezing glutes', 'Feet too far from body'],
    tips: ['Great glute activation', 'Add barbell for hip thrust', 'Hold at top 2-3 seconds'] },
  { id: 'e35', name: 'Wall Sit', muscleGroup: 'legs', secondaryMuscles: ['abs'], difficulty: 'beginner', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Back flat against wall', 'Slide down to 90 degrees', 'Hold position', 'Keep core braced'],
    mistakes: ['Knees past toes', 'Not reaching 90 degrees', 'Leaning forward'],
    tips: ['Great endurance builder', 'Time your holds', 'Add weight on thighs for progression'] },
  { id: 'e36', name: 'Kettlebell Swing', muscleGroup: 'legs', secondaryMuscles: ['back', 'abs', 'shoulders'], difficulty: 'intermediate', equipment: 'kettlebell', isHome: true, isGym: true,
    instructions: ['Stand with feet wider than shoulders', 'Hinge at hips, swing kettlebell back', 'Drive hips forward explosively', 'Let kettlebell float to chest height'],
    mistakes: ['Squatting instead of hinging', 'Using arms to lift', 'Rounding back'],
    tips: ['Power comes from hips', 'One of best conditioning exercises', 'Start light to learn form'] },

  // SHOULDERS (10)
  { id: 'e37', name: 'Overhead Press', muscleGroup: 'shoulders', secondaryMuscles: ['triceps'], difficulty: 'intermediate', equipment: 'barbell', isHome: false, isGym: true,
    instructions: ['Bar at front rack position', 'Press overhead', 'Lock out arms', 'Lower to shoulders'],
    mistakes: ['Arching back excessively', 'Pressing in front', 'Elbows flaring'],
    tips: ['Squeeze glutes for stability', 'Straight bar path', 'Full lockout'] },
  { id: 'e38', name: 'Lateral Raises', muscleGroup: 'shoulders', secondaryMuscles: [], difficulty: 'beginner', equipment: 'dumbbell', isHome: true, isGym: true,
    instructions: ['Hold dumbbells at sides', 'Raise arms to shoulder height', 'Lead with elbows', 'Lower slowly'],
    mistakes: ['Swinging weight', 'Going above shoulder height', 'Shrugging traps'],
    tips: ['Light weight high reps', 'Slight forward lean', 'Control the negative'] },
  { id: 'e39', name: 'Arnold Press', muscleGroup: 'shoulders', secondaryMuscles: ['triceps'], difficulty: 'intermediate', equipment: 'dumbbell', isHome: true, isGym: true,
    instructions: ['Start with palms facing you', 'Rotate and press overhead', 'Reverse the motion', 'Full range rotation'],
    mistakes: ['Not rotating fully', 'Using momentum', 'Going too heavy'],
    tips: ['Hits all three delt heads', 'Created by Arnold Schwarzenegger', 'Smooth continuous motion'] },
  { id: 'e40', name: 'Upright Row', muscleGroup: 'shoulders', secondaryMuscles: ['biceps'], difficulty: 'intermediate', equipment: 'barbell', isHome: false, isGym: true,
    instructions: ['Hold bar with narrow grip', 'Pull to chin level', 'Lead with elbows', 'Lower slowly'],
    mistakes: ['Grip too narrow causing wrist pain', 'Pulling too high', 'Internal rotation'],
    tips: ['Use wider grip for safety', 'Don\'t go above chin', 'Can use dumbbells'] },
  { id: 'e41', name: 'Reverse Flyes', muscleGroup: 'shoulders', secondaryMuscles: ['back'], difficulty: 'beginner', equipment: 'dumbbell', isHome: true, isGym: true,
    instructions: ['Bend forward at hips', 'Raise arms out to sides', 'Squeeze rear delts', 'Lower with control'],
    mistakes: ['Using momentum', 'Not bending enough', 'Too heavy weight'],
    tips: ['Essential for shoulder balance', 'Light weight is key', 'Targets rear delts'] },
  { id: 'e42', name: 'Pike Push-Ups', muscleGroup: 'shoulders', secondaryMuscles: ['triceps'], difficulty: 'intermediate', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Start in downward dog position', 'Bend elbows, lower head to floor', 'Push back up', 'Keep hips high'],
    mistakes: ['Hips dropping', 'Not going deep enough', 'Wrong hand position'],
    tips: ['Progression to handstand push-ups', 'Elevate feet for harder version', 'Great shoulder builder'] },
  { id: 'e43', name: 'Front Raise', muscleGroup: 'shoulders', secondaryMuscles: [], difficulty: 'beginner', equipment: 'dumbbell', isHome: true, isGym: true,
    instructions: ['Hold dumbbells at thighs', 'Raise one arm to eye level', 'Lower slowly', 'Alternate arms'],
    mistakes: ['Swinging weight', 'Going too high', 'Arching back'],
    tips: ['Targets front delts', 'Keep core engaged', 'Can use plate instead'] },
  { id: 'e44', name: 'Cable Lateral Raise', muscleGroup: 'shoulders', secondaryMuscles: [], difficulty: 'intermediate', equipment: 'cable', isHome: false, isGym: true,
    instructions: ['Stand sideways to cable', 'Grab low handle with far hand', 'Raise arm to shoulder height', 'Lower with control'],
    mistakes: ['Leaning away', 'Using body momentum', 'Going too heavy'],
    tips: ['Constant tension advantage', 'Great for mind-muscle connection', 'Cross-body setup'] },
  { id: 'e45', name: 'Handstand Push-Ups', muscleGroup: 'shoulders', secondaryMuscles: ['triceps', 'abs'], difficulty: 'advanced', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Kick up to handstand against wall', 'Lower head toward floor', 'Press back to full extension', 'Maintain balance'],
    mistakes: ['Flaring elbows', 'Not engaging core', 'Arching back'],
    tips: ['Ultimate bodyweight shoulder exercise', 'Start with wall support', 'Build with pike push-ups first'] },
  { id: 'e46', name: 'Shrugs', muscleGroup: 'shoulders', secondaryMuscles: [], difficulty: 'beginner', equipment: 'dumbbell', isHome: true, isGym: true,
    instructions: ['Hold heavy dumbbells at sides', 'Shrug shoulders up to ears', 'Squeeze traps at top', 'Lower slowly'],
    mistakes: ['Rolling shoulders', 'Not pausing at top', 'Going too light'],
    tips: ['Heavy weight works best', 'Hold at top 2 seconds', 'Builds trap thickness'] },

  // BICEPS (8)
  { id: 'e47', name: 'Barbell Curl', muscleGroup: 'biceps', secondaryMuscles: [], difficulty: 'beginner', equipment: 'barbell', isHome: false, isGym: true,
    instructions: ['Stand with bar at arm length', 'Curl bar to shoulders', 'Squeeze biceps at top', 'Lower slowly'],
    mistakes: ['Swinging body', 'Elbows moving forward', 'Going too heavy'],
    tips: ['Keep elbows pinned to sides', 'Control the negative', 'Full range of motion'] },
  { id: 'e48', name: 'Hammer Curls', muscleGroup: 'biceps', secondaryMuscles: [], difficulty: 'beginner', equipment: 'dumbbell', isHome: true, isGym: true,
    instructions: ['Hold dumbbells with neutral grip', 'Curl to shoulders', 'Keep thumbs up', 'Lower with control'],
    mistakes: ['Swinging', 'Rotating wrists', 'Incomplete range'],
    tips: ['Targets brachialis', 'Builds arm width', 'Alternate or simultaneous'] },
  { id: 'e49', name: 'Preacher Curls', muscleGroup: 'biceps', secondaryMuscles: [], difficulty: 'intermediate', equipment: 'barbell', isHome: false, isGym: true,
    instructions: ['Rest arms on preacher bench', 'Curl bar up', 'Squeeze at top', 'Lower fully'],
    mistakes: ['Not going full range', 'Lifting off pad', 'Going too heavy'],
    tips: ['Strict isolation', 'Great for peak contraction', 'Use EZ bar for wrist comfort'] },
  { id: 'e50', name: 'Concentration Curls', muscleGroup: 'biceps', secondaryMuscles: [], difficulty: 'beginner', equipment: 'dumbbell', isHome: true, isGym: true,
    instructions: ['Sit on bench, elbow on inner thigh', 'Curl dumbbell up', 'Squeeze at peak', 'Lower slowly'],
    mistakes: ['Using shoulder to lift', 'Not full range', 'Rushing reps'],
    tips: ['Best for mind-muscle connection', 'Slow controlled reps', 'Focus on peak squeeze'] },
  { id: 'e51', name: 'Cable Curls', muscleGroup: 'biceps', secondaryMuscles: [], difficulty: 'beginner', equipment: 'cable', isHome: false, isGym: true,
    instructions: ['Stand facing cable', 'Grip bar underhand', 'Curl to shoulders', 'Lower with constant tension'],
    mistakes: ['Leaning back', 'Moving elbows', 'Partial reps'],
    tips: ['Constant tension throughout', 'Great pump exercise', 'Try different attachments'] },
  { id: 'e52', name: 'Incline Dumbbell Curl', muscleGroup: 'biceps', secondaryMuscles: [], difficulty: 'intermediate', equipment: 'dumbbell', isHome: false, isGym: true,
    instructions: ['Sit on incline bench', 'Let arms hang naturally', 'Curl dumbbells up', 'Full stretch at bottom'],
    mistakes: ['Bench too upright', 'Swinging arms', 'Partial range'],
    tips: ['Maximum stretch on biceps', 'One of best bicep exercises', 'Go lighter than standing curls'] },
  { id: 'e53', name: 'Chin-Up Hold', muscleGroup: 'biceps', secondaryMuscles: ['back'], difficulty: 'intermediate', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Pull chin above bar', 'Hold at top position', 'Squeeze biceps', 'Lower slowly after hold'],
    mistakes: ['Kipping up', 'Not holding long enough', 'Losing grip'],
    tips: ['Builds isometric strength', 'Great for grip', 'Hold 5-10 seconds'] },
  { id: 'e54', name: 'Resistance Band Curls', muscleGroup: 'biceps', secondaryMuscles: [], difficulty: 'beginner', equipment: 'resistance band', isHome: true, isGym: false,
    instructions: ['Stand on band', 'Grip handles underhand', 'Curl to shoulders', 'Lower with control'],
    mistakes: ['Not enough tension', 'Moving elbows', 'Rushing'],
    tips: ['Perfect for home workouts', 'Increasing resistance at top', 'Great for rehab'] },

  // TRICEPS (8)
  { id: 'e55', name: 'Tricep Dips', muscleGroup: 'triceps', secondaryMuscles: ['chest', 'shoulders'], difficulty: 'intermediate', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Grip parallel bars or bench edge', 'Keep body upright', 'Lower to 90 degrees', 'Press back up'],
    mistakes: ['Going too deep', 'Flaring elbows', 'Leaning forward for triceps'],
    tips: ['Stay upright for tricep focus', 'Bench dips for beginners', 'Add weight for progression'] },
  { id: 'e56', name: 'Skull Crushers', muscleGroup: 'triceps', secondaryMuscles: [], difficulty: 'intermediate', equipment: 'barbell', isHome: false, isGym: true,
    instructions: ['Lie flat with bar overhead', 'Lower bar to forehead', 'Extend arms back up', 'Keep elbows fixed'],
    mistakes: ['Elbows flaring', 'Bar going to chest', 'Too much weight'],
    tips: ['Use EZ bar for wrist comfort', 'Lower behind head for more stretch', 'Great mass builder'] },
  { id: 'e57', name: 'Cable Pushdown', muscleGroup: 'triceps', secondaryMuscles: [], difficulty: 'beginner', equipment: 'cable', isHome: false, isGym: true,
    instructions: ['Grip rope or bar attachment', 'Press down from chest', 'Lock out at bottom', 'Return with control'],
    mistakes: ['Leaning too far forward', 'Elbows moving', 'Using body weight'],
    tips: ['Squeeze at bottom', 'Try rope for extra extension', 'Keep elbows pinned'] },
  { id: 'e58', name: 'Overhead Tricep Extension', muscleGroup: 'triceps', secondaryMuscles: [], difficulty: 'beginner', equipment: 'dumbbell', isHome: true, isGym: true,
    instructions: ['Hold dumbbell overhead with both hands', 'Lower behind head', 'Extend back up', 'Keep elbows close'],
    mistakes: ['Elbows flaring out', 'Arching back', 'Not full range'],
    tips: ['Great for long head', 'Can use cable too', 'Keep upper arms stationary'] },
  { id: 'e59', name: 'Close-Grip Bench Press', muscleGroup: 'triceps', secondaryMuscles: ['chest'], difficulty: 'intermediate', equipment: 'barbell', isHome: false, isGym: true,
    instructions: ['Grip bar inside shoulder width', 'Lower to lower chest', 'Press up keeping elbows tucked', 'Full lockout'],
    mistakes: ['Grip too narrow', 'Flaring elbows', 'Bouncing off chest'],
    tips: ['Hits all three tricep heads', 'Heavy compound movement', 'Great for overall mass'] },
  { id: 'e60', name: 'Kickbacks', muscleGroup: 'triceps', secondaryMuscles: [], difficulty: 'beginner', equipment: 'dumbbell', isHome: true, isGym: true,
    instructions: ['Hinge forward, upper arm parallel to floor', 'Extend forearm back', 'Squeeze tricep', 'Return with control'],
    mistakes: ['Moving upper arm', 'Using momentum', 'Not full extension'],
    tips: ['Light weight works best', 'Focus on squeeze', 'Great finisher exercise'] },
  { id: 'e61', name: 'Diamond Push-Ups', muscleGroup: 'triceps', secondaryMuscles: ['chest'], difficulty: 'intermediate', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Hands together in diamond shape', 'Lower chest to hands', 'Push back up', 'Keep elbows close'],
    mistakes: ['Elbows flaring', 'Incomplete range', 'Hips sagging'],
    tips: ['Best bodyweight tricep exercise', 'Can do on knees', 'Pause at bottom'] },
  { id: 'e62', name: 'Band Pushdown', muscleGroup: 'triceps', secondaryMuscles: [], difficulty: 'beginner', equipment: 'resistance band', isHome: true, isGym: false,
    instructions: ['Anchor band above head', 'Grab ends, press down', 'Lock out at bottom', 'Return slowly'],
    mistakes: ['Not enough resistance', 'Moving elbows', 'Partial range'],
    tips: ['Great home alternative', 'Mimic cable pushdown', 'Easy to set up'] },

  // ABS (10)
  { id: 'e63', name: 'Plank', muscleGroup: 'abs', secondaryMuscles: ['shoulders'], difficulty: 'beginner', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Forearms on floor', 'Body in straight line', 'Engage core', 'Hold position'],
    mistakes: ['Hips too high or low', 'Holding breath', 'Looking up'],
    tips: ['Foundation core exercise', 'Time your progress', 'Add variations for challenge'] },
  { id: 'e64', name: 'Crunches', muscleGroup: 'abs', secondaryMuscles: [], difficulty: 'beginner', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Lie on back, knees bent', 'Curl shoulders off floor', 'Squeeze abs', 'Lower slowly'],
    mistakes: ['Pulling neck', 'Using momentum', 'Full sit-up motion'],
    tips: ['Short range of motion', 'Hands behind head lightly', 'Exhale on crunch'] },
  { id: 'e65', name: 'Hanging Leg Raises', muscleGroup: 'abs', secondaryMuscles: [], difficulty: 'advanced', equipment: 'bodyweight', isHome: false, isGym: true,
    instructions: ['Hang from pull-up bar', 'Raise legs to parallel', 'Control the descent', 'Don\'t swing'],
    mistakes: ['Swinging body', 'Using momentum', 'Bending at hips only'],
    tips: ['Best lower ab exercise', 'Start with knee raises', 'Slow and controlled'] },
  { id: 'e66', name: 'Russian Twists', muscleGroup: 'abs', secondaryMuscles: [], difficulty: 'intermediate', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Sit with feet elevated', 'Lean back 45 degrees', 'Rotate torso side to side', 'Touch floor each side'],
    mistakes: ['Moving arms not torso', 'Dropping feet', 'Going too fast'],
    tips: ['Great for obliques', 'Add weight for challenge', 'Keep feet elevated'] },
  { id: 'e67', name: 'Mountain Climbers', muscleGroup: 'abs', secondaryMuscles: ['shoulders', 'legs'], difficulty: 'beginner', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Start in push-up position', 'Drive knees to chest alternately', 'Keep hips level', 'Maintain fast pace'],
    mistakes: ['Hips bouncing up', 'Not driving knees in', 'Losing form with speed'],
    tips: ['Cardio and core combined', 'Great warm-up exercise', 'Count time not reps'] },
  { id: 'e68', name: 'Ab Wheel Rollout', muscleGroup: 'abs', secondaryMuscles: ['shoulders', 'back'], difficulty: 'advanced', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Kneel with wheel in front', 'Roll forward extending body', 'Maintain tight core', 'Roll back to start'],
    mistakes: ['Collapsing lower back', 'Going too far', 'Not bracing core'],
    tips: ['Start from knees', 'One of hardest ab exercises', 'Progress to standing slowly'] },
  { id: 'e69', name: 'Dead Bug', muscleGroup: 'abs', secondaryMuscles: [], difficulty: 'beginner', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Lie on back, arms up, knees at 90', 'Extend opposite arm and leg', 'Keep lower back pressed to floor', 'Return and switch'],
    mistakes: ['Arching lower back', 'Moving too fast', 'Not breathing properly'],
    tips: ['Great for core stability', 'Physio-recommended', 'Focus on keeping back flat'] },
  { id: 'e70', name: 'Bicycle Crunches', muscleGroup: 'abs', secondaryMuscles: [], difficulty: 'beginner', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Lie on back, hands behind head', 'Bring knee to opposite elbow', 'Extend other leg straight', 'Alternate continuously'],
    mistakes: ['Pulling neck', 'Going too fast', 'Not full rotation'],
    tips: ['One of best ab exercises per study', 'Slow controlled reps', 'Full rotation each rep'] },
  { id: 'e71', name: 'Cable Crunch', muscleGroup: 'abs', secondaryMuscles: [], difficulty: 'intermediate', equipment: 'cable', isHome: false, isGym: true,
    instructions: ['Kneel at cable station', 'Hold rope behind head', 'Crunch down curling spine', 'Return with control'],
    mistakes: ['Hinging at hips', 'Using arms to pull', 'Not rounding spine'],
    tips: ['Progressive overload for abs', 'Focus on spinal flexion', 'Don\'t sit back on heels'] },
  { id: 'e72', name: 'Side Plank', muscleGroup: 'abs', secondaryMuscles: ['shoulders'], difficulty: 'beginner', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Lie on side, forearm on floor', 'Stack feet or stagger', 'Lift hips forming straight line', 'Hold position'],
    mistakes: ['Hips dropping', 'Rolling forward or back', 'Holding breath'],
    tips: ['Essential for obliques', 'Add hip dips for dynamic version', 'Both sides equally'] },

  // CARDIO (8)
  { id: 'e73', name: 'Burpees', muscleGroup: 'cardio', secondaryMuscles: ['chest', 'legs', 'abs'], difficulty: 'intermediate', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Stand tall', 'Drop to push-up position', 'Do a push-up', 'Jump up explosively'],
    mistakes: ['Skipping the push-up', 'Not jumping high', 'Worm-like movement'],
    tips: ['Ultimate full-body exercise', 'Great for HIIT', 'Scale by removing jump or push-up'] },
  { id: 'e74', name: 'Jump Rope', muscleGroup: 'cardio', secondaryMuscles: ['legs', 'shoulders'], difficulty: 'beginner', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Hold rope handles at hips', 'Jump just high enough to clear rope', 'Land softly on balls of feet', 'Use wrist rotation'],
    mistakes: ['Jumping too high', 'Using arms too much', 'Landing flat-footed'],
    tips: ['Amazing cardio conditioner', 'Burns more calories than running', 'Start with 30 second intervals'] },
  { id: 'e75', name: 'Box Jumps', muscleGroup: 'cardio', secondaryMuscles: ['legs'], difficulty: 'intermediate', equipment: 'bodyweight', isHome: false, isGym: true,
    instructions: ['Stand facing box', 'Swing arms and jump onto box', 'Land softly with bent knees', 'Step back down'],
    mistakes: ['Landing too hard', 'Box too high', 'Not using arms'],
    tips: ['Builds explosive power', 'Start with lower box', 'Step down don\'t jump down'] },
  { id: 'e76', name: 'Sprint Intervals', muscleGroup: 'cardio', secondaryMuscles: ['legs'], difficulty: 'advanced', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Sprint for 20-30 seconds', 'Walk or jog 40-60 seconds', 'Repeat 8-12 rounds', 'Cool down after'],
    mistakes: ['No warm-up', 'Going too hard too early', 'Not enough recovery'],
    tips: ['Best fat burning cardio', 'Better than steady state', 'Track distances for progress'] },
  { id: 'e77', name: 'Battle Ropes', muscleGroup: 'cardio', secondaryMuscles: ['shoulders', 'abs'], difficulty: 'intermediate', equipment: 'bodyweight', isHome: false, isGym: true,
    instructions: ['Hold rope ends at hip height', 'Create waves alternating arms', 'Keep core braced', 'Maintain rhythm'],
    mistakes: ['Standing too upright', 'Not using legs', 'Losing rhythm'],
    tips: ['Amazing upper body cardio', 'Try different wave patterns', '30 second intervals'] },
  { id: 'e78', name: 'High Knees', muscleGroup: 'cardio', secondaryMuscles: ['abs', 'legs'], difficulty: 'beginner', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Stand in place', 'Drive knees up to waist height', 'Pump arms', 'Maintain fast pace'],
    mistakes: ['Leaning back', 'Knees not high enough', 'Landing on heels'],
    tips: ['Great warm-up', 'Improves running form', 'Can be done anywhere'] },
  { id: 'e79', name: 'Jumping Jacks', muscleGroup: 'cardio', secondaryMuscles: ['shoulders', 'legs'], difficulty: 'beginner', equipment: 'bodyweight', isHome: true, isGym: true,
    instructions: ['Start with feet together', 'Jump feet apart and arms overhead', 'Jump back to start', 'Maintain rhythm'],
    mistakes: ['Not full range', 'Landing too hard', 'Losing coordination'],
    tips: ['Classic warm-up exercise', 'Good for active recovery', 'Can be made harder with squat jacks'] },
  { id: 'e80', name: 'Stair Sprints', muscleGroup: 'cardio', secondaryMuscles: ['legs', 'abs'], difficulty: 'intermediate', equipment: 'bodyweight', isHome: true, isGym: false,
    instructions: ['Find a flight of stairs', 'Sprint up as fast as possible', 'Walk down for recovery', 'Repeat 6-10 rounds'],
    mistakes: ['Not watching steps', 'Going too fast downstairs', 'No warm-up'],
    tips: ['Amazing leg and cardio workout', 'Walk down for safety', 'Use stairs at home or outdoors'] },
];

export const preBuiltPlans = [
  {
    id: 'plan1',
    name: 'Beginner Strength',
    description: '3 days/week full body program for beginners',
    difficulty: 'beginner' as const,
    duration: '4 weeks',
    frequency: '3 days/week',
    days: [
      { name: 'Day A', exercises: ['e25', 'e2', 'e14', 'e37', 'e47', 'e63'] },
      { name: 'Day B', exercises: ['e15', 'e26', 'e19', 'e38', 'e57', 'e64'] },
      { name: 'Day C', exercises: ['e33', 'e1', 'e16', 'e41', 'e48', 'e67'] },
    ]
  },
  {
    id: 'plan2',
    name: 'Muscle Building',
    description: '5-day split for intermediate lifters',
    difficulty: 'intermediate' as const,
    duration: '8 weeks',
    frequency: '5 days/week',
    days: [
      { name: 'Chest', exercises: ['e2', 'e3', 'e4', 'e5', 'e8'] },
      { name: 'Back', exercises: ['e13', 'e14', 'e18', 'e17', 'e21'] },
      { name: 'Shoulders', exercises: ['e37', 'e38', 'e39', 'e41', 'e46'] },
      { name: 'Legs', exercises: ['e25', 'e27', 'e28', 'e30', 'e31'] },
      { name: 'Arms', exercises: ['e47', 'e49', 'e56', 'e57', 'e50'] },
    ]
  },
  {
    id: 'plan3',
    name: 'Fat Loss Program',
    description: 'High intensity circuits for maximum calorie burn',
    difficulty: 'intermediate' as const,
    duration: '6 weeks',
    frequency: '4 days/week',
    days: [
      { name: 'Circuit A', exercises: ['e73', 'e25', 'e1', 'e67', 'e74'] },
      { name: 'Circuit B', exercises: ['e36', 'e13', 'e66', 'e78', 'e75'] },
      { name: 'Circuit C', exercises: ['e29', 'e8', 'e63', 'e73', 'e76'] },
      { name: 'Circuit D', exercises: ['e33', 'e42', 'e68', 'e77', 'e79'] },
    ]
  },
  {
    id: 'plan4',
    name: 'Push Pull Legs',
    description: 'Classic PPL split for balanced development',
    difficulty: 'intermediate' as const,
    duration: '12 weeks',
    frequency: '6 days/week',
    days: [
      { name: 'Push', exercises: ['e2', 'e3', 'e37', 'e38', 'e56', 'e57'] },
      { name: 'Pull', exercises: ['e13', 'e14', 'e21', 'e47', 'e48', 'e51'] },
      { name: 'Legs', exercises: ['e25', 'e27', 'e28', 'e30', 'e31', 'e32'] },
    ]
  },
  {
    id: 'plan5',
    name: 'Home Workout',
    description: 'No equipment needed, train anywhere',
    difficulty: 'beginner' as const,
    duration: '4 weeks',
    frequency: '4 days/week',
    days: [
      { name: 'Upper Body', exercises: ['e1', 'e6', 'e22', 'e42', 'e55'] },
      { name: 'Lower Body', exercises: ['e29', 'e34', 'e32', 'e35', 'e36'] },
      { name: 'Core & Cardio', exercises: ['e63', 'e66', 'e67', 'e73', 'e70'] },
      { name: 'Full Body', exercises: ['e1', 'e33', 'e13', 'e64', 'e74'] },
    ]
  },
  {
    id: 'plan6',
    name: 'Full Body Power',
    description: 'Compound movements for strength gains',
    difficulty: 'advanced' as const,
    duration: '6 weeks',
    frequency: '3 days/week',
    days: [
      { name: 'Workout A', exercises: ['e25', 'e2', 'e14', 'e37', 'e15'] },
      { name: 'Workout B', exercises: ['e15', 'e3', 'e13', 'e59', 'e25'] },
      { name: 'Workout C', exercises: ['e25', 'e7', 'e14', 'e2', 'e15'] },
    ]
  },
];

export const getExerciseById = (id: string) => exercises.find(e => e.id === id);
export const getExercisesByMuscle = (muscle: string) => exercises.filter(e => e.muscleGroup === muscle);
export const getExercisesByDifficulty = (diff: string) => exercises.filter(e => e.difficulty === diff);
export const getHomeExercises = () => exercises.filter(e => e.isHome);
export const getGymExercises = () => exercises.filter(e => e.isGym);
